# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [ ]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 11 ms
Wall time: 671 ms


### Exercício 2

In [ ]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [2]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8] = 0
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [ ]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [4]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [ ]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [6]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#terceira linha
arr2d[2]

array([7, 8, 9])

In [8]:
#primeira e segunda linha, segunda e terceira coluna
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

### Exercício 5

In [11]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [13]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [14]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [15]:
resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [16]:
A = np.arange(10)
print(A)
np.save('array_a', A)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [18]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [19]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [24]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [25]:
data = resp.json()
data[0]['title']

'ENH: initial support for non-nano Timestamp'

In [26]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    46839        ENH: initial support for non-nano Timestamp   
1    46838      BUG: 'NAType' object has no attribute 'dtype'   
2    46837  BUG: Setting multiple values via .loc produces...   
3    46836             TST: GH32822 data types in frame manip   
4    46835                                DOC: fix rsplit doc   
5    46834                               Fix concat docstring   
6    46833  BUG: `pd.MultiIndex.reindex` when the levels a...   
7    46832                         added test for issue_21758   
8    46830    stopped numeric_only=True from dropping columns   
9    46829         added tests for the test_groupby_dropna.py   
10   46828          ENH: ints_to_pytimedelta support non-nano   
11   46826  BUG: Inconsistent return type for groupby-resa...   
12   46825         DOC: write guide for how to replace append   
13   46824                           add code and sample test   
14   46823  PERF: `pd.read_csv` is very slow when used wit...   
15   46822  BUG: Construction of DataFrame works with empt...   
16   46820  BUG: CategoricalDtype is not refresh after ind...   
17   46819  BUG: Timedelta.total_seconds method is returni...   
18   46818  BUG: can't insert scalar value into empty data...   
19   46817  ENH: adding saving and reading of dataframe `a...   
20   46816        REF: avoid ravel in DatetimeArray.to_period   
21   46815         ENH: Add axis=None for statistical methods   
22   46814  BUG: Runtime warning with groupby/tail when `N...   
23   46813  BUG: Newer Version Pandas loc does not return ...   
24   46812  BUG: Error writing DataFrame with categorical ...   
25   46811      BUG: parsing nanoseconds incorrect resolution   
26   46810  BUG: `pd.read_excel` writing numbers with .0 i...   
27   46809  ENH: allow functions in `keep` parameter of `d...   
28   46808              BUG: TimeStamp index rolling problems   
29   46807  BUG: Inconsistent result of in-place Series.re...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3                                                  []  open  
4   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
5                                                  []  open  
6   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
7                                                  []  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
11  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
12  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
13                                                 []  open  
14  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
15  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
19                                                 []  open  
20                                                 []  open  
21                                                 []  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
25                                                 []  open  
26  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
27  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
28  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
29  [{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0...  open

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [29]:
data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [30]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5),
 ('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [31]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5
3     Natal  Rio Grande do Norte  1.25         6
4    Recife           Pernambuco  2.60         3
5  Londrina               Paraná  1.70         5

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
